server:
  port: 8848

spring:
  application:
    name: subscriptions
  mvc:
    view:
      prefix: /
      suffix: .html 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 定位页面的目录到static/下


   
